### ISSUE TITLE
创建服务碰到的问题？

### ISSUE THREAD

**Issue by hyz4566758** [everythingbest/dubbo-postman#2]
1、jar包和pom文件下载问题，我们用的nexus版本是3.0.0-03，没法用地址
suffixUrl = "?r="+"releases&g="+groupId+"&a="+artifactId+"&v="+version+"&e=jar"; 进行下载。
2、处理api.jar的所有依赖,通过执行maven命令: 'mvn dependency:copy-dependencies -DoutputDirectory=./lib -DexcludeScope=provided -U'，这个会从maven的仓库进行下载，而不会走私服，会导致parent的pom下载失败。
请帮忙看看。

**Comment by everythingbest** [comment]
> 1、jar包和pom文件下载问题，我们用的nexus版本是3.0.0-03，没法用地址
> suffixUrl = "?r="+"releases&g="+groupId+"&a="+artifactId+"&v="+version+"&e=jar"; 进行下载。
> 2、处理api.jar的所有依赖,通过执行maven命令: 'mvn dependency:copy-dependencies -DoutputDirectory=./lib -DexcludeScope=provided -U'，这个会从maven的仓库进行下载，而不会走私服，会导致parent的pom下载失败。
> 请帮忙看看。

问题1：
我需要看下，理论上走的http，jar包的地址都是拼接的，可能格式有所不一致，你可以在你们的nexus里面点击某个jar，然后右键复制链接地址出来，观察下路径，然后可以提交给我也可以你自行修改评价这个地址代码的地方
问题2：
你需要找到你们公司统一的setting.xml文件，这个文件里面有各个maven仓库地址的代理，默认都会优先从私服下载。
如果你本地构建过java项目，那么这个文件通常在你的~\users\用户名\.m2目录里面[windows系统]。
把项目的resources/config/setting.xml改成你们公司的统一的setting.xml文件就可以了。
如果你们公司没有统一的setting.xml，你可以自行编辑项目的resources/config/setting.xml，把里面的地址改成响应你们公司私服地址即可。

**Comment by hyz4566758** [comment]
> > 1、jar包和pom文件下载问题，我们用的nexus版本是3.0.0-03，没法用地址
> > suffixUrl = "?r="+"releases&g="+groupId+"&a="+artifactId+"&v="+version+"&e=jar"; 进行下载。
> > 2、处理api.jar的所有依赖,通过执行maven命令: 'mvn dependency:copy-dependencies -DoutputDirectory=./lib -DexcludeScope=provided -U'，这个会从maven的仓库进行下载，而不会走私服，会导致parent的pom下载失败。
> > 请帮忙看看。
> 
> 问题1：
> 我需要看下，理论上走的http，jar包的地址都是拼接的，可能格式有所不一致，你可以在你们的nexus里面点击某个jar，然后右键复制链接地址出来，观察下路径，然后可以提交给我也可以你自行修改评价这个地址代码的地方
> 问题2：
> 你需要找到你们公司统一的setting.xml文件，这个文件里面有各个maven仓库地址的代理，默认都会优先从私服下载。
> 如果你本地构建过java项目，那么这个文件通常在你的~\users\用户名.m2目录里面[windows系统]。
> 把项目的resources/config/setting.xml改成你们公司的统一的setting.xml文件就可以了。
> 如果你们公司没有统一的setting.xml，你可以自行编辑项目的resources/config/setting.xml，把里面的地址改成响应你们公司私服地址即可。

问题1: pom地址如：http://ip:port/repository/maven-snapshots/com/xxx/pay/frame-log/1.1.14-SNAPSHOT/frame-log-1.1.14-20190428.102346-2.pom  ，在snapshots时，这种url不好拼接。因为时间戳不知道。
问题2: 我用的是mac， 在命令行执行那个命令时能从私服下载，但是代码执行时会从外面的仓库下载。所以看看是不是命令上面指定一下配置的路径。用-s指定可以。

**Comment by everythingbest** [comment]
> > > 1、jar包和pom文件下载问题，我们用的nexus版本是3.0.0-03，没法用地址
> > > suffixUrl = "?r="+"releases&g="+groupId+"&a="+artifactId+"&v="+version+"&e=jar"; 进行下载。
> > > 2、处理api.jar的所有依赖,通过执行maven命令: 'mvn dependency:copy-dependencies -DoutputDirectory=./lib -DexcludeScope=provided -U'，这个会从maven的仓库进行下载，而不会走私服，会导致parent的pom下载失败。
> > > 请帮忙看看。
> > 
> > 
> > 问题1：
> > 我需要看下，理论上走的http，jar包的地址都是拼接的，可能格式有所不一致，你可以在你们的nexus里面点击某个jar，然后右键复制链接地址出来，观察下路径，然后可以提交给我也可以你自行修改评价这个地址代码的地方
> > 问题2：
> > 你需要找到你们公司统一的setting.xml文件，这个文件里面有各个maven仓库地址的代理，默认都会优先从私服下载。
> > 如果你本地构建过java项目，那么这个文件通常在你的~\users\用户名.m2目录里面[windows系统]。
> > 把项目的resources/config/setting.xml改成你们公司的统一的setting.xml文件就可以了。
> > 如果你们公司没有统一的setting.xml，你可以自行编辑项目的resources/config/setting.xml，把里面的地址改成响应你们公司私服地址即可。
> 
> 问题1: pom地址如：http://ip:port/repository/maven-snapshots/com/xxx/pay/frame-log/1.1.14-SNAPSHOT/frame-log-1.1.14-20190428.102346-2.pom ，在snapshots时，这种url不好拼接。因为时间戳不知道。
> 问题2: 我用的是mac， 在命令行执行那个命令时能从私服下载，但是代码执行时会从外面的仓库下载。所以看看是不是命令上面指定一下配置的路径。用-s指定可以。

问题1:
在nexus里面有两个地址，一个是你把鼠标放在jar上在浏览器底部会显示的，你贴出的这个是点击Artifact看到的。所以这个是没有问题的。
问题2：
你命令执行，默认会选择你用户目录下面的.m2目录，代码里面会选择代码里面的resources/config/setting.xml这个文件，复制到dubbo.api.jar.dir这属性指定的目录下面的.m2目录下面。
总结：
上面的问题根本原因是，你需要把你用户目录，类似 /users/username/.m2/setting.xml覆盖项目的resources/config/setting.xml这个文件。如果你 /users/username/.m2/setting.xml不存在，你需要手动修改项目的resources/config/setting.xml这个文件各项配置，
参考：https://blog.csdn.net/u012152619/article/details/51485152

**Comment by hyz4566758** [comment]
> .m2

问题2解决了，莫名其妙好了。后面不行我再看看你的方法。
问题1你再看看，我们nexus版本不太一样，我这边鼠标放上去跟点击的地址是一样的。你可以装个试看看。https://blog.csdn.net/qq250782929/article/details/51605965

**Comment by kayleyang** [comment]
![image](https://user-images.githubusercontent.com/8251856/89164679-f5e77f00-d5a9-11ea-8f90-af5485a8c721.png)
如图所示，SNAPSHOT的jar包和pom文件是上面的地址栏加上下面的具体文件名，会存在一个随机数，可以通过分析maven-metadata.xml文件来获取最新时间戳的jar包和pom文件的路径
![image](https://user-images.githubusercontent.com/8251856/89164907-4eb71780-d5aa-11ea-9cc1-863aee1f79eb.png)

**Comment by everythingbest** [comment]
> ![image](https://user-images.githubusercontent.com/8251856/89164679-f5e77f00-d5a9-11ea-8f90-af5485a8c721.png)
> 如图所示，SNAPSHOT的jar包和pom文件是上面的地址栏加上下面的具体文件名，会存在一个随机数，可以通过分析maven-metadata.xml文件来获取最新时间戳的jar包和pom文件的路径
> ![image](https://user-images.githubusercontent.com/8251856/89164907-4eb71780-d5aa-11ea-9cc1-863aee1f79eb.png)

这个是maven里面的快照版本，这个程序里面是通过maven的原生命令下载的，不需要手动下载，这个自动支持的
