### ISSUE TITLE
nexus有密码的话，如何配置呢？

### ISSUE THREAD

**Issue by fengzzzz** [everythingbest/dubbo-postman#3]
你好，
请问nexus有密码的话，如何配置呢？

**Comment by everythingbest** [comment]
> 你好，
> 请问nexus有密码的话，如何配置呢？

公司内部的nexus一般不会需要用户名密码访问的，通常nexus只是管理员有个账号可以登录进行jar的管理的。在这个项目里面不需要配置密码，只需要指定那个下载的重定向地址即可。

**Comment by fengzzzz** [comment]
这边我看到有下载jar包，然后下载完了，还要mavenCopyDependencies？直接用下载的jar包不行吗？

**Comment by everythingbest** [comment]
> 这边我看到有下载jar包，然后下载完了，还要mavenCopyDependencies？直接用下载的jar包不行吗？

直接下载的只是api.jar，这个api.jar依赖了其他的jar需要下载，不然不能正确加载类。

**Comment by roll0and1** [comment]
我这边使用您的下载jar 和 pom 的方式好像无法正确下载，可否有个通用下载文件的方式，url 拼接存在差异性。

**Comment by everythingbest** [comment]
> 我这边使用您的下载jar 和 pom 的方式好像无法正确下载，可否有个通用下载文件的方式，url 拼接存在差异性。


无法下载可以看下具体的错误信息；目前是通过url的拼接方式从nexus里面下载，暂时为了做到比较自动化，没有更好的方式来处理这个情况，当使用这个工具的时候，可以结合自己公司内部使用的nexus，来填充可变的部分。
不过后续可以研究下nexus的这块内容，以更好的实现通用吧。
