### ISSUE TITLE
非常感谢作者的开源精神，十分佩服和感激，我来给作者提几个 后面需求，希望作者认真考虑，非常NICE的工具

### ISSUE THREAD

**Issue by long5192004** [everythingbest/dubbo-postman#34]
非常感谢作者的开源精神，十分佩服和感激，我来给作者提几个 后面需求，希望作者认真考虑，非常NICE的工具

这个工具做的非常NICE，但是还不够强大，给作者提几点建议，希望能够采纳。如果这几个做出来了，将会是个非常非常好的互联网DUBBO测试工具，我认为。

1.  在场景测试中一定要加入 参数化，比如 service3的入参 需要service1和service2的出参作为变量传入，这样才能把整个业务场景串起来集成。实际业务测试中做到真正的无需写 服务测试代码了。

2.  最好有一个批量生成工程的 功能，这样我可以把所有添加的场景的测试 在jenkins上持续集成跑起来了。

**Comment by everythingbest** [comment]
> 非常感谢作者的开源精神，十分佩服和感激，我来给作者提几个 后面需求，希望作者认真考虑，非常NICE的工具
> 
> 这个工具做的非常NICE，但是还不够强大，给作者提几点建议，希望能够采纳。如果这几个做出来了，将会是个非常非常好的互联网DUBBO测试工具，我认为。
> 
> 1. 在场景测试中一定要加入 参数化，比如 service3的入参 需要service1和service2的出参作为变量传入，这样才能把整个业务场景串起来集成。实际业务测试中做到真正的无需写 服务测试代码了。
> 2. 最好有一个批量生成工程的 功能，这样我可以把所有添加的场景的测试 在jenkins上持续集成跑起来了。

第一个在场景测试脚本里面已经有这个功能了
![image](https://user-images.githubusercontent.com/53523451/119925147-721ed900-bfa7-11eb-93c2-dd78114bdb1e.png)

第二个如果有需要可以自行修改，也是非常简单的功能。
