### ISSUE TITLE
pom文件解析失败

### ISSUE THREAD

**Issue by Achang-007** [everythingbest/dubbo-postman#39]
这个是什么问题，下载下来的pom文件解析失败
ERROR [http-nio-8080-exec-4] o.a.m.DefaultMaven:error:89 [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml: Expected root element 'project' but found 'html' (position: START_TAG seen ... @1:6) @ line 1, column 6

**Comment by everythingbest** [comment]
> D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml

D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml 文件格式有问题：Expected root element 'project' but found 'html' (position: START_TAG seen ... @1:6) @ line 1, column 6

**Comment by Achang-007** [comment]
> > D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml
> 
> D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml 文件格式有问题：Expected root element 'project' but found 'html' (position: START_TAG seen ... @1:6) @ line 1, column 6

嗯嗯， 对的下载的pom文件格式有问题，现在问题是， 我改了你对应setting文件里面的私服地址和账号密码 都换成了我的，但是目前还是有问题， 生成pom文件不能用。尴尬了，知道原因，但是不知道具体原因。

**Comment by everythingbest** [comment]
> 不知道

**Comment by everythingbest** [comment]
> > > D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml
> > 
> > 
> > D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml 文件格式有问题：Expected root element 'project' but found 'html' (position: START_TAG seen ... @1:6) @ line 1, column 6
> 
> 嗯嗯， 对的下载的pom文件格式有问题，现在问题是， 我改了你对应setting文件里面的私服地址和账号密码 都换成了我的，但是目前还是有问题， 生成pom文件不能用。尴尬了，知道原因，但是不知道具体原因。

需要看下 D:\tools\user\tmp\dubbo-postman\0_0_1-SNAPSHOT_xxx\pom.xml 这个文件具体内容，看具体是哪里配置出错。
