### ISSUE TITLE
发送服务

### ISSUE THREAD

**Issue by GitHubWangX20170628** [everythingbest/dubbo-postman#5]
发送服务的时候一直报975 opening socket to server xxx.xx.xx/ xxx.xx.xx:9090,will not attempt to authenticate using SASL ;
为什么是9090端口，程序启动初始的时候连接2181正常。为什么发送服务连的时9090而且连接不上

**Comment by everythingbest** [comment]
> 发送服务的时候一直报975 opening socket to server xxx.xx.xx/ xxx.xx.xx:9090,will not attempt to authenticate using SASL ;
> 为什么是9090端口，程序启动初始的时候连接2181正常。为什么发送服务连的时9090而且连接不上

不是特别明确你描述的问题在哪一步，可以截个图或者把服务相应的日志贴下。

**Comment by GitHubWangX20170628** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: everythingbest <notifications@github.com&gt;
发送时间: 2020年3月17日 15:01
收件人: everythingbest/dubbo-postman <dubbo-postman@noreply.github.com&gt;
抄送: GitHubWangX20170628 <153261609@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[everythingbest/dubbo-postman] 发送服务 (#5)





  
发送服务的时候一直报975 opening socket to server xxx.xx.xx/ xxx.xx.xx:9090,will not attempt to authenticate using SASL ;
 为什么是9090端口，程序启动初始的时候连接2181正常。为什么发送服务连的时9090而且连接不上
  
不是特别明确你描述的问题在哪一步，可以截个图或者把服务相应的日志贴下。

**Comment by GitHubWangX20170628** [comment]
截图哪个按钮

**Comment by GitHubWangX20170628** [comment]
![Uploading 2b062db345d669e2c1ac98643cc4cc1.jpg…]()
日志
