### ISSUE TITLE
访问服务菜单点击send按钮报错

### ISSUE THREAD

**Issue by GitHubWangX20170628** [everythingbest/dubbo-postman#6]
截图上传不了有啊 有qq吗

**Comment by GitHubWangX20170628** [comment]
Opening socket connection to server 10.70.42.99/10.70.42.99:9090. Will not attempt to authenticate using SASL
org.apache.zookeeper.ClientCnxn [1102] - Session 0x0 for server unexpected error,closing socket connection and attempting reconnect


反复再打这些日志
为什么zk连接的是9090 而不是2181

**Comment by everythingbest** [comment]
> Opening socket connection to server 10.70.42.99/10.70.42.99:9090. Will not attempt to authenticate using SASL
> org.apache.zookeeper.ClientCnxn [1102] - Session 0x0 for server unexpected error,closing socket connection and attempting reconnect
> 
> 反复再打这些日志
> 为什么zk连接的是9090 而不是2181

你在集群里面配置了你的zk集群地址吗，配置格式是这样的：
192.168.11.29:2181
如果是多个就用英文逗号给开
然后输入验证码 ，再提交保存

**Comment by everythingbest** [comment]
可以发我邮箱 x875645317@163.com

**Comment by GitHubWangX20170628** [comment]
好了谢谢，注册中心没填端口只填了地址。加上端口就好了。但是居然也能创建成功

**Comment by GitHubWangX20170628** [comment]
场景测试这块有没有更多的说明，特别是场景脚本怎么编辑，有那些脚本命令

**Comment by everythingbest** [comment]
> 场景测试这块有没有更多的说明，特别是场景脚本怎么编辑，有那些脚本命令

这里给个说明的demo:

//全局变量1:reqs代表请求数组,reqs[0]代表第一个请求
//全局变量2:rst代表结果变量map

//全局方法1:获取第一个请求的orderDTO.tradeDtoList属性:
//var result = getProp(reqs[0],"orderDTO.tradeDtoList")
//if(result !== false){//表示获取成功
//   rst.put("result",result);
//}

//全局方法2:设置请求的属性值orderDTO.orderId 为123
//var isOk = setProp(reqs[0],"orderDTO.orderId",123);
//if(isOk === true){//表示设置成功
//	rst.put("设置成功",isOk);
//}else{
// 设置失败,这时不用进行后面的请求了,没有意义
//}

//全局方法3:发送请求,得到返回值对象
//var responseObj = send(reqs[0]);//如果请求失败，返回的时错误描述内容
//rst.put("responseObj",responseObj);
