### ISSUE TITLE
创建服务时下载pom文件错误

### ISSUE THREAD

**Issue by yechenxi1** [everythingbest/dubbo-postman#7]
创建服务时可以下载pom文件，但是该pom文件实际上对应nexus页面的html。已经把config下的setting文件用公司的setting文件替换了。麻烦帮忙解答一下，谢谢！

**Comment by everythingbest** [comment]
> 创建服务时可以下载pom文件，但是该pom文件实际上对应nexus页面的html。已经把config下的setting文件用公司的setting文件替换了。麻烦帮忙解答一下，谢谢！

nexus.url: 私服仓库地址 ，检查下这个是否配置正确。
可以通过这种方式拿到具体的地址：
1，你把本地仓库里面你的某个jar目录删除，然后在项目里面执行 "mvn compile" ，然后在日志里面可以看到下载的这个jar及对应的pom的地址，然后根据下面的代码，你应该能判断你的nexus地址前缀了，然后设置到项目的熟悉里面，重启服务。
“然后根据下面的代码” ：
src/main/java/com/dubbo/postman/service/maven/MavenProcessor.java
 String buildPomUrl(String groupId,String artifactId,String version){
        
        String upperV = version.trim().toUpperCase();
    
        String suffixUrl;
    
        if(upperV.endsWith("SNAPSHOT")){
        
            suffixUrl = "?r="+"snapshots&g="+groupId+"&a="+artifactId+"&v="+version+"&e=pom";
        
        }else{
        
            suffixUrl = "?r="+"releases&g="+groupId+"&a="+artifactId+"&v="+version+"&e=pom";
        }
    
        return nexusUrl+suffixUrl;
    }

**Comment by yechenxi1** [comment]
看到的地址是类似gygoods/gygoodsbizcore-facade/0.0.7-SNAPSHOT/gygoodsbizcore-facade-0.0.7-20200324.094859-4.jar这样的，和您的拼接方式不太一样。请问像这种带时间戳的拼接有什么好的解决方案吗。谢谢您。

**Comment by everythingbest** [comment]
> 看到的地址是类似gygoods/gygoodsbizcore-facade/0.0.7-SNAPSHOT/gygoodsbizcore-facade-0.0.7-20200324.094859-4.jar这样的，和您的拼接方式不太一样。请问像这种带时间戳的拼接有什么好的解决方案吗。谢谢您。

**Comment by everythingbest** [comment]
- 

1. 

- [ ] @ #### _****_

**Comment by everythingbest** [comment]
![dubbopostman-nexus (2)](https://user-images.githubusercontent.com/53523451/77421163-4bdf3580-6e06-11ea-9aad-1da234072653.png)

**Comment by yechenxi1** [comment]
请问一下 什么时候会出现ThirdPartOrderManageFacade加载到内存失败:java.lang.ClassNotFoundException这种情况呢

**Comment by everythingbest** [comment]
> 请问一下 什么时候会出现ThirdPartOrderManageFacade加载到内存失败:java.lang.ClassNotFoundException这种情况呢

这个是你们自己的api依赖的jar包没有在你们的仓库里面，有可能对于dubbo-postman的创建有影响，可以自行看下能不能访问。如果有问题可以查看这个类对应的是在那个jar里面，让相关的同事上传到nexus，然后再刷新或者从新创建服务就可以了。

**Comment by yechenxi1** [comment]
好的 谢谢您啊
